query ALL_CURRENCIES {
  viewer {
    allCurrencies(where: {active: {eq: true}}, orderBy:{field: symbol, direction: ASC}) {
      edges {
        node {
          active
          algo
          balance_path
          balance_url
          block_reward
          coinMarketCapName
          cryptoid
          insight
          iquidus
          masternode
          name
          symbol
          whattomineID
          yiimp_explorer
        }
      }
    }
  }
}
